using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

namespace AgriEnergyConnect.Models.ViewModels
{
    // The MessageViewModel class is a ViewModel used to transfer message data
    // between the Razor Pages views and the application layers.
    // It includes validation attributes to ensure data integrity and user-friendly error messages.
    public class MessageViewModel
    {
        // The unique identifier for the message.
        // This is a required field and is automatically generated by the database.
        public int MessageId { get; set; }

        // The subject or title of the message.
        // This is a required field with a maximum length of 100 characters.
        // Validation ensures that the subject is provided and does not exceed the character limit.
        [Required(ErrorMessage = "Subject is required.")]
        [StringLength(100, ErrorMessage = "Subject cannot exceed 100 characters.")]
        [Display(Name = "Subject")]
        public string Subject { get; set; }

        // The content or body of the message.
        // This is a required field and can contain any length of text.
        // Validation ensures that the content is provided.
        [Required(ErrorMessage = "Message content is required.")]
        [Display(Name = "Message")]
        public string Content { get; set; }

        // The unique identifier of the recipient of the message.
        // This is a required field and represents the user who will receive the message.
        [Required(ErrorMessage = "Recipient is required.")]
        [Display(Name = "Recipient")]
        public int RecipientId { get; set; }

        // Read-only properties for display

        // The name of the recipient of the message.
        // This is a read-only property used for display purposes.
        public string RecipientName { get; set; }

        // The name of the sender of the message.
        // This is a read-only property used for display purposes.
        public string SenderName { get; set; }

        // The date and time when the message was sent.
        // This is a read-only property used for display purposes.
        public DateTime SendDate { get; set; }

        // Indicates whether the message has been read by the recipient.
        // This is a read-only property used for display purposes.
        public bool IsRead { get; set; }
    }

    // The MessageListViewModel class is a ViewModel used to transfer summarized message data
    // for listing or preview purposes in Razor Pages views.
    public class MessageListViewModel
    {
        // The unique identifier for the message.
        // This is a required field and is automatically generated by the database.
        public int MessageId { get; set; }

        // The subject or title of the message.
        // This is used for display purposes in message lists.
        public string Subject { get; set; }

        // The name of the sender of the message.
        // This is used for display purposes in message lists.
        public string SenderName { get; set; }

        // The name of the recipient of the message.
        // This is used for display purposes in message lists.
        public string RecipientName { get; set; }

        // The date and time when the message was sent.
        // This is used for display purposes in message lists.
        public DateTime SendDate { get; set; }

        // Indicates whether the message has been read by the recipient.
        // This is used for display purposes in message lists.
        public bool IsRead { get; set; }

        // Indicates whether the message is part of the sent messages list.
        // This is used to distinguish between sent and received messages.
        public bool IsSent { get; set; }
    }
}