using System.ComponentModel.DataAnnotations;

namespace AgriEnergyConnect.Models.ViewModels
{
    // The ProductViewModel class is a ViewModel used to transfer product data
    // between the Razor Pages views and the application layers.
    // It includes validation attributes to ensure data integrity and user-friendly error messages.
    public class ProductViewModel
    {
        // The unique identifier for the product.
        // This is a required field and is automatically generated by the database.
        public int ProductId { get; set; }

        // The name of the product.
        // This is a required field with a maximum length of 100 characters.
        // Validation ensures that the name is provided and does not exceed the character limit.
        [Required(ErrorMessage = "Product name is required.")]
        [StringLength(100, ErrorMessage = "Product name cannot exceed 100 characters.")]
        [Display(Name = "Product Name")]
        public string Name { get; set; }

        // The category of the product (e.g., fruits, vegetables, grains).
        // This is a required field, and validation ensures that a category is selected.
        [Required(ErrorMessage = "Category is required.")]
        [Display(Name = "Category")]
        public string Category { get; set; }

        // The date when the product was produced.
        // This is a required field and must be a valid date.
        // The DisplayFormat attribute ensures the date is displayed in "dd-MM-yyyy" format.
        [Required(ErrorMessage = "Production date is required.")]
        [DataType(DataType.Date)]
        [Display(Name = "Production Date")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public DateTime ProductionDate { get; set; }

        // A brief description of the product.
        // This is an optional field with a maximum length of 500 characters.
        // Validation ensures that the description does not exceed the character limit.
        [StringLength(500, ErrorMessage = "Description cannot exceed 500 characters.")]
        [Display(Name = "Description")]
        public string Description { get; set; }

        // The unique identifier of the farmer who owns the product.
        // This is set from the current user's session and is not exposed to the user.
        public int FarmerId { get; set; }
    }
}