name: Build and Test

on:
  push:
    branches:
      - main
      - development
      - 'feature/**'
      - 'chore/**'
  pull_request:
    branches:
      - main
      - development
      - 'feature/**'
      - 'chore/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install linters
        run: |
          npm install eslint stylelint --save-dev

      - name: Run ESLint
        run: npx eslint "**/*.js"

      - name: Run Stylelint
        run: npx stylelint "**/*.css"

    continue-on-error: true  # lint failures won’t block PR merges
